CREATE TABLE partidos (
    id INT NOT NULL AUTO_INCREMENT,
    jornada INT NOT NULL,
    local VARCHAR(50) NOT NULL,
    visitante VARCHAR(50) NOT NULL,
    golesLocal INT NOT NULL,
    golesVisitante INT NOT NULL,
    PRIMARY KEY (id)
);


INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (1,'Alavés','Levante',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (1,'Athletic Bilbao','Barcelona',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (1,'Atlético Madrid','Getafe',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (1,'Celta Vigo','Real Madrid',1,3);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (1,'Espanyol','Sevilla',0,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (1,'Leganés','Osasuna',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (1,'Mallorca','Eibar',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (1,'Valencia','Real Sociedad',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (1,'Villarreal','Granada',4,4);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (1,'Betis','Valladolid',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (2,'Eibar','Osasuna',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (2,'Granada','Sevilla',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (2,'Levante','Villarreal',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (2,'Real Madrid','Valladolid',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (2,'Real Sociedad','Mallorca',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (2,'Barcelona','Betis',5,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (2,'Getafe','Athletic Bilbao',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (2,'Celta Vigo','Valencia',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (2,'Alavés','Espanyol',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (2,'Atlético Madrid','Leganés',3,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (3,'Osasuna','Barcelona',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (3,'Espanyol','Granada',0,3);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (3,'Sevilla','Celta Vigo',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (3,'Villarreal','Real Madrid',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (3,'Valencia','Mallorca',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (3,'Leganés','Atlético Madrid',0,3);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (3,'Athletic Bilbao','Real Sociedad',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (3,'Betis','Leganés',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (3,'Getafe','Alavés',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (3,'Valladolid','Osasuna',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (4,'Real Madrid','Levante',3,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (4,'Osasuna','Betis',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (4,'Real Sociedad','Eibar',3,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (4,'Barcelona','Valencia',5,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (4,'Mallorca','Atlético Madrid',0,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (4,'Granada','Barcelona',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (4,'Leganés','Villarreal',0,3);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (4,'Celta Vigo','Granada',0,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (4,'Espanyol','Real Sociedad',1,3);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (4,'Alavés','Sevilla',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (4,'Athletic Bilbao','Valladolid',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (5,'Levante','Eibar',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (5,'Atlético Madrid','Celta Vigo',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (5,'Valencia','Leganés',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (5,'Betis','Getafe',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (5,'Valladolid','Granada',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (5,'Villarreal','Valladolid',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (5,'Osasuna','Real Betis',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (5,'Real Sociedad','Alavés',3,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (5,'Barcelona','Sevilla',4,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (5,'Eibar','Espanyol',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (6,'Espanyol','Valladolid',0,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (6,'Sevilla','Real Sociedad',3,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (6,'Getafe','Barcelona',0,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (6,'Celta Vigo','Athletic Bilbao',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (6,'Granada','Leganés',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (6,'Real Madrid','Osasuna',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (6,'Alavés','Mallorca',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (6,'Eibar','Villarreal',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (6,'Levante','Osasuna',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (6,'Betis','Eibar',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (6,'Valladolid','Granada',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (7,'Real Sociedad','Betis',3,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (7,'Villarreal','Celta Vigo',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (7,'Valencia','Alavés',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (7,'Osasuna','Villarreal',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (7,'Mallorca','Real Madrid',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (7,'Leganés','Levante',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (7,'Athletic Bilbao','Valladolid',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (7,'Barcelona','Sevilla',4,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (7,'Espanyol','Villarreal',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (7,'Getafe','Granada',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (8,'Granada','Osasuna',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (8,'Valladolid','Eibar',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (8,'Real Madrid','Betis',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (8,'Celta Vigo','Athletic Bilbao',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (8,'Levante','Eibar',0,3);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (8,'Alavés','Celta Vigo',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (8,'Villarreal','Alavés',4,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (8,'Sevilla','Levante',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (8,'Espanyol','Valladolid',0,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (8,'Barcelona','Real Madrid',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (8,'Leganés','Getafe',0,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (9,'Eibar','Barcelona',0,3);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (9,'Real Madrid','Granada',4,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (9,'Athletic Bilbao','Espanyol',3,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (9,'Betis','Eibar',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (9,'Osasuna','Valencia',3,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (9,'Alavés','Celta Vigo',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (9,'Valladolid','Mallorca',3,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (9,'Levante','Espanyol',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (9,'Granada','Osasuna',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (9,'Getafe','Real Sociedad',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (10,'Barcelona','Real Valladolid',5,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (10,'Valencia','Sevilla',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (10,'Real Sociedad','Levante',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (10,'Celta Vigo','Real Sociedad',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (10,'Levante','Eibar',0,3);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (10,'Real Valladolid','Real Madrid',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (10,'Espanyol','Villarreal',1,3);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (10,'Osasuna','Alavés',4,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (10,'Mallorca','Villarreal',3,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (10,'Getafe','Celta Vigo',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (10,'Leganés','Mallorca',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (11,'Eibar','Leganés',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (11,'Sevilla','Atlético Madrid',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (11,'Real Madrid','Betis',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (11,'Villarreal','Athletic Bilbao',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (11,'Valladolid','Mallorca',3,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (11,'Barcelona','Celta Vigo',4,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (11,'Granada','Celta Vigo',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (11,'Valencia','Granada',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (11,'Levante','Barcelona',3,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (11,'Alavés','Mallorca',3,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (12,'Celta Vigo','Real Valladolid',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (12,'Atlético Madrid','Espanyol',3,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (12,'Real Sociedad','Leganés',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (12,'Betis','Valencia',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (12,'Eibar','Alavés',0,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (12,'Mallorca','Betis',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (12,'Levante','Mallorca',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (12,'Real Valladolid','Sevilla',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (12,'Barcelona','Real Sociedad',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (12,'Granada','Atlético Madrid',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (12,'Osasuna','Athletic Bilbao',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (13,'Leganés','Celta Vigo',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (13,'Sevilla','Leganés',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (13,'Valencia','Villarreal',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (13,'Alavés','Real Madrid',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (13,'Real Sociedad','Eibar',4,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (13,'Mallorca','Betis',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (13,'Espanyol','Osasuna',2,4);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (13,'Betis','Real Sociedad',3,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (13,'Athletic Bilbao','Granada',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (13,'Atlético Madrid','Barcelona',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (13,'Valladolid','Celta Vigo',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (14,'Barcelona','Mallorca',5,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (14,'Real Madrid','Espanyol',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (14,'Osasuna','Sevilla',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (14,'Villarreal','Atlético Madrid',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (14,'Eibar','Getafe',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (14,'Levante','Valencia',2,4);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (14,'Granada','Alavés',3,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (14,'Betis','Athletic Bilbao',3,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (14,'Celta Vigo','Mallorca',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (14,'Leganés','Valladolid',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (15,'Atlético Madrid','Osasuna',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (15,'Espanyol','Real Betis',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (15,'Sevilla','Villarreal',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (15,'Alavés','Leganés',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (15,'Valladolid','Real Sociedad',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (15,'Barcelona','Real Madrid',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (15,'Athletic Bilbao','Eibar',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (15,'Mallorca','Celta Vigo',5,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (15,'Getafe','Levante',4,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (15,'Valencia','Granada',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (16,'Real Madrid','Espanyol',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (16,'Villarreal','Atlético Madrid',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (16,'Levante','Valencia',2,4);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (16,'Eibar','Getafe',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (16,'Celta Vigo','Mallorca',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (16,'Granada','Levante',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (16,'Betis','Athletic Bilbao',3,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (16,'Leganés','Celta Vigo',3,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (16,'Real Sociedad','Barcelona',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (16,'Osasuna','Sevilla',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (16,'Valladolid','Alavés',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (17,'Barcelona','Alavés',4,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (17,'Atlético Madrid','Levante',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (17,'Espanyol','Real Betis',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (17,'Getafe','Valladolid',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (17,'Sevilla','Mallorca',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (17,'Athletic Bilbao','Eibar',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (17,'Valencia','Real Madrid',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (17,'Leganés','Eibar',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (17,'Real Sociedad','Villarreal',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (17,'Celta Vigo','Osasuna',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (18,'Osasuna','Real Sociedad',3,4);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (18,'Real Betis','Alavés',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (18,'Valencia','Eibar',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (18,'Real Madrid','Athletic Bilbao',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (18,'Levante','Celta Vigo',3,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (18,'Valladolid','Leganés',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (18,'Villarreal','Getafe',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (18,'Mallorca','Sevilla',0,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (18,'Barcelona','Granada',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (18,'Espanyol','Atlético Madrid',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (19,'Atlético Madrid','Levante',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (19,'Alavés','Betis',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (19,'Eibar','Granada',3,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (19,'Athletic Bilbao','Celta Vigo',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (19,'Getafe','Villarreal',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (19,'Real Sociedad','Valladolid',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (19,'Mallorca','Valencia',4,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (19,'Leganés','Getafe',0,3);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (19,'Osasuna','Real Betis',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (19,'Sevilla','Atlético Madrid',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (19,'Barcelona','Espanyol',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (20,'Valencia','Barcelona',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (20,'Levante','Alavés',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (20,'Villarreal','Eibar',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (20,'Celta Vigo','Espanyol',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (20,'Betis','Real Sociedad',3,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (20,'Granada','Espanyol',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (20,'Valladolid','Real Madrid',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (20,'Leganés','Getafe',0,3);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (20,'Atlético Madrid','Osasuna',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (20,'Mallorca','Valencia',4,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (21,'Espanyol','Mallorca',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (21,'Real Madrid','Celta Vigo',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (21,'Barcelona','Getafe',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (21,'Atlético Madrid','Granada',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (21,'Sevilla','Alavés',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (21,'Levante','Leganés',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (21,'Villarreal','Osasuna',3,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (21,'Valladolid','Villarreal',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (21,'Eibar','Betis',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (21,'Real Sociedad','Athletic Bilbao',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (22,'Real Betis','Barcelona',2,3);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (22,'Valencia','Celta Vigo',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (22,'Osasuna','Levante',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (22,'Mallorca','Valladolid',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (22,'Athletic Bilbao','Osasuna',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (22,'Eibar','Sociedad',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (22,'Granada','Real Valladolid',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (22,'Leganés','Real Betis',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (22,'Alavés','Espanyol',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (22,'Getafe','Valencia',3,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (23,'Granada','Valladolid',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (23,'Atlético de Madrid','Granada',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (23,'Real Madrid','Celta de Vigo',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (23,'Espanyol','Mallorca',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (23,'Valencia','Celta de Vigo',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (23,'Real Sociedad','Athletic de Bilbao',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (23,'Levante','Leganés',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (23,'Osasuna','Real Madrid',1,4);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (23,'Villarreal','Levante',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (23,'Sevilla','Espanyol',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (24,'Alavés','Athletic de Bilbao',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (24,'Levante','Real Madrid',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (24,'Barcelona','Eibar',5,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (24,'Atlético de Madrid','Villarreal',3,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (24,'Valladolid','Real Sociedad',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (24,'Leganés','Deportivo Alavés',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (24,'Sevilla','Espanyol',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (24,'Mallorca','Getafe',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (24,'Valencia','Celta de Vigo',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (24,'Granada','Osasuna',0,3);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (25,'Celta de Vigo','Leganés',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (25,'Mallorca','Alavés',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (25,'Real Madrid','Barcelona',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (25,'Valencia','Betis',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (25,'Eibar','Levante',3,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (25,'Sevilla','Osasuna',3,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (25,'Athletic de Bilbao','Villarreal',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (25,'Getafe','Sevilla',0,3);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (25,'Real Sociedad','Valladolid',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (25,'Granada','Celta de Vigo',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (26,'Villarreal','Leganés',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (26,'Real Madrid','Celta de Vigo',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (26,'Barcelona','Real Sociedad',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (26,'Eibar','Mallorca',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (26,'Atlético de Madrid','Sevilla',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (26,'Valladolid','Athletic de Bilbao',1,4);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (26,'Levante','Granada',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (26,'Osasuna','Espanyol',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (26,'Getafe','Celta de Vigo',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (26,'Betis','Valencia',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (27,'Levante','Granada',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (27,'Real Madrid','Barcelona',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (27,'Real Sociedad','Valencia',3,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (27,'Betis','Real Madrid',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (27,'Valencia','Atlético Madrid',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (27,'Sevilla','Valladolid',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (27,'Espanyol','Alavés',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (27,'Osasuna','Eibar',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (27,'Getafe','Celta',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (27,'Villarreal','Leganés',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (28,'Eibar','Real Sociedad',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (28,'Mallorca','Barcelona',0,4);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (28,'Atlético Madrid','Sevilla',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (28,'Valladolid','Celta',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (28,'Levante','Valencia',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (28,'Granada','Getafe',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (28,'Espanyol','Alavés',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (28,'Betis','Real Madrid',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (28,'Athletic Bilbao','Villarreal',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (28,'Leganés','Osasuna',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (29,'Valencia','Levante',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (29,'Sevilla','Betis',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (29,'Athletic Bilbao','Mallorca',3,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (29,'Celta','Villarreal',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (29,'Granada','Getafe',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (29,'Osasuna','Atlético Madrid',0,5);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (29,'Valladolid','Leganés',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (29,'Barcelona','Leganés',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (29,'Eibar','Real Madrid',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (29,'Alavés','Real Sociedad',0,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (30,'Eibar','Valencia',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (30,'Villarreal','Sevilla',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (30,'Mallorca','Celta',5,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (30,'Real Sociedad','Osasuna',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (30,'Athletic Bilbao','Real Madrid',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (30,'Leganés','Valladolid',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (30,'Barcelona','Athletic Bilbao',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (30,'Atlético Madrid','Alavés',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (30,'Getafe','Espanyol',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (30,'Betis','Granada',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (31,'Villarreal','Sevilla',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (31,'Eibar','Athletic Club',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (31,'Levante','Real Betis',4,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (31,'Real Madrid','Eibar',3,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (31,'Real Sociedad','Osasuna',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (31,'Valladolid','Getafe',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (31,'Alavés','Real Sociedad',0,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (31,'Barcelona','Atlético Madrid',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (31,'Valencia','Osasuna',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (31,'Athletic Club','Mallorca',3,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (32,'Sevilla FC','Real Valladolid',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (32,'Athletic Club','Real Madrid',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (32,'Atlético de Madrid','Deportivo Alavés',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (32,'Celta de Vigo','FC Barcelona',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (32,'Espanyol','Levante UD',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (32,'Getafe CF','Real Sociedad',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (32,'Granada CF','Eibar',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (32,'Leganés','Valencia CF',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (32,'Osasuna','CD Leganés',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (32,'Villarreal CF','Mallorca',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (33,'Deportivo Alavés','Granada CF',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (33,'Real Madrid','Getafe CF',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (33,'Valencia CF','Valladolid CF',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (33,'Villarreal CF','FC Barcelona',1,4);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (33,'Real Sociedad','SD Eibar',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (33,'Levante UD','Real Betis',4,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (33,'Sevilla FC','RCD Mallorca',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (33,'CD Leganés','Valencia CF',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (33,'CA Osasuna','Celta de Vigo',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (33,'RC Celta de Vigo','Atlético de Madrid',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (34,'SD Eibar','CA Osasuna',0,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (34,'Atlético de Madrid','Real Betis',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (34,'RC Celta de Vigo','Real Betis',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (34,'Levante UD','Real Sociedad',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (34,'Valladolid CF','Deportivo Alavés',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (34,'FC Barcelona','Espanyol',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (34,'Getafe CF','Villarreal CF',1,3);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (34,'RCD Mallorca','CD Leganés',1,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (34,'Athletic Club','Sevilla FC',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (34,'Valencia CF','Real Madrid',1,3);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (35,'Deportivo Alavés','Getafe CF',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (35,'Real Betis','CD Leganés',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (35,'Villarreal CF','Real Sociedad',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (35,'Granada CF','Valencia CF',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (35,'FC Barcelona','Atlético de Madrid',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (35,'RCD Espanyol','Eibar',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (35,'Athletic Club','Sevilla FC',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (35,'Real Madrid','Deportivo Alavés',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (35,'Levante UD','RC Celta de Vigo',4,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (35,'SD Eibar','CA Osasuna',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (36,'Sevilla FC','Real Mallorca',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (36,'CA Osasuna','Celta de Vigo',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (36,'Eibar','Leganés',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (36,'Real Sociedad','Granada CF',2,3);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (36,'Valencia CF','Espanyol',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (36,'Athletic Club','Real Madrid',0,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (36,'CD Leganés','Valencia CF',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (36,'Barcelona','Osasuna',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (36,'Villarreal','Getafe CF',1,3);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (36,'Levante UD','Athletic Club',1,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (37,'Getafe CF','Atlético de Madrid',0,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (37,'Real Madrid','Villarreal CF',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (37,'RCD Espanyol','Celta de Vigo',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (37,'CA Osasuna','Cádiz CF',2,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (37,'Levante UD','Getafe CF',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (37,'Granada CF','Athletic Club',4,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (37,'Sevilla FC','Valencia CF',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (37,'SD Eibar','Real Valladolid',3,1);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (37,'Real Sociedad','Sevilla FC',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (37,'CD Leganés','Real Madrid',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (38,'Granada CF','Athletic Club',4,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (38,'CA Osasuna','Mallorca',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (38,'Real Valladolid','Real Betis',2,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (38,'CD Leganés','Real Madrid',2,2);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (38,'Barcelona','Alavés',5,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (38,'Espanyol','Celta de Vigo',0,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (38,'Levante UD','Getafe CF',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (38,'Sevilla FC','Valencia CF',1,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (38,'Villarreal','Eibar',4,0);
INSERT INTO partidos (jornada, local, visitante, golesLocal, golesVisitante) VALUES (38,'Atlético de Madrid','Real Sociedad',1,1);
