create table tarea_19_LOCALIDAD(
COD_LOCALIDAD NUMBER PRIMARY KEY,
NOMBRE VARCHAR2 (20) not null
);
create table tarea_19_PUB(
COD_PUB number primary key,
NOMBRE varchar2 (20) not null,
LICENCIA_FISCAL varchar2 (20) not null,
DOMICILIO VARCHAR2 (10),
FECHA_APERTURA DATE NOT NULL,
HORARIO VARCHAR2 (4) NOT NULL CHECK(HORARIO IN ('HOR1','HOR2','HOR3')),
COD_LOCALIDAD NUMBER NOT NULL,
FOREIGN KEY (tarea_19_COD_LOCALIDAD) REFERENCES tarea_19_LOCALIDAD(COD_LOCALIDAD)
);
CREATE TABLE tarea_19_TITULAR(
DNI_TITULAR NUMBER PRIMARY KEY,
NOMBRE VARCHAR2 (20) not null,
DOMICILIO VARCHAR2 (40),
COD_PUB NUMBER NOT NULL,
FOREIGN KEY (COD_PUB) REFERENCES tarea_19_PUB(COD_PUB)
);
CREATE TABLE tarea_19_EMPLEADO(
DNI_EMPLEADO NUMBER PRIMARY KEY,
NOMBRE VARCHAR2 (20) NOT NULL,
DOMICILIO VARCHAR2 (40)
);
CREATE TABLE tarea_19_EXISTENCIAS(
COD_ARTICULO NUMBER PRIMARY KEY,
NOMBRE VARCHAR2 (20),
CONSTRAINT NOMBRE_NN NOT NULL (NOMBRE,COD_ARTICULO),
CANTIDAD NUMBER (20) NOT NULL,
PRECIO NUMBER (20) NOT NULL CHECK(PRECIO>0),
COD_PUB NUMBER NOT NULL,
FOREIGN KEY (COD_PUB) REFERENCES tarea_19_PUB(COD_PUB)
);
CREATE TABLE tarea_19_PUB_EMPLEADO(
COD_PUB NUMBER NOT NULL,
DNI_EMPLEADO NUMBER NOT NULL,
FUNCION VARCHAR2 (20) NOT NULL CHECK (FUNCION IN('CAMARERO', 'SEGURIDAD', 'LIMPIEZA')),
PRIMARY KEY (COD_PUB, DNI_EMPLEADO),
FOREIGN KEY (COD_PUB) REFERENCES tarea_19_PUB(COD_PUB),
FOREIGN KEY (DNI_EMPLEADO) REFERENCES tarea_19_EMPLEADO(DNI_EMPLEADO)
);
