SELECT NOMBRE FROM INFOR_PRODUCTO;

SELECT NOMBRE, PRECIO FROM INFOR_PRODUCTO;

SELECT * FROM INFOR_PRODUCTO;

SELECT NOMBRE, (PRECIO*1.09) AS EUROS, PRECIO AS USD FROM INFOR_PRODUCTO;

SELECT LOWER(NOMBRE) AS NOMBRES_MINUS, PRECIO FROM INFOR_PRODUCTO;

SELECT nombre, UPPER(SUBSTR(nombre, 1, 2)) AS dos_primeros_mayusculas FROM INFOR_fabricante;

SELECT NOMBRE, ROUND(PRECIO) AS PRECIO_REDOND FROM INFOR_PRODUCTO; 

SELECT NOMBRE, TRUNC(PRECIO) AS PRECIO_TRUNCADO FROM INFOR_PRODUCTO;

SELECT id_fabricante FROM infor_producto;

SELECT NOMBRE FROM INFOR_FABRICANTE ORDER BY NOMBRE ASC;

SELECT NOMBRE FROM INFOR_FABRICANTE ORDER BY NOMBRE DESC;

SELECT NOMBRE FROM INFOR_PRODUCTO ORDER BY NOMBRE ASC, PRECIO DESC;

SELECT * FROM INFOR_fabricante WHERE ROWNUM <= 5;

SELECT * FROM INFOR_PRODUCTO WHERE PRECIO = (SELECT MIN(PRECIO)FROM INFOR_PRODUCTO);

SELECT * FROM INFOR_PRODUCTO WHERE PRECIO =(SELECT MAX(PRECIO)FROM INFOR_PRODUCTO);

SELECT NOMBRE FROM INFOR_PRODUCTO WHERE ID_FABRICANTE = 2;

SELECT NOMBRE,PRECIO FROM INFOR_PRODUCTO WHERE PRECIO >= 120;

SELECT NOMBRE, PRECIO FROM INFOR_PRODUCTO WHERE PRECIO >= 400;

SELECT NOMBRE,PRECIO FROM INFOR_PRODUCTO WHERE PRECIO >= 80 AND PRECIO<=300;

SELECT NOMBRE, PRECIO FROM INFOR_PRODUCTO WHERE PRECIO BETWEEN 60 AND 200;

SELECT * FROM INFOR_PRODUCTO WHERE PRECIO > 200 AND ID_FABRICANTE = 6;

SELECT * FROM INFOR_PRODUCTO WHERE ID_FABRICANTE IN (1,3,5);

SELECT NOMBRE,PRECIO,(PRECIO*100) AS CENTIMOS FROM INFOR_PRODUCTO;

SELECT NOMBRE FROM INFOR_FABRICANTE WHERE NOMBRE LIKE 'S%';

SELECT NOMBRE FROM INFOR_FABRICANTE WHERE NOMBRE LIKE '%e';

SELECT NOMBRE FROM INFOR_FABRICANTE WHERE NOMBRE LIKE '%w%' or nombre like '%W%';

SELECT NOMBRE FROM INFOR_FABRICANTE WHERE LENGTH(NOMBRE)=4;

SELECT NOMBRE FROM INFOR_PRODUCTO WHERE NOMBRE LIKE '%Monitor%' and precio < 215;

SELECT NOMBRE, PRECIO FROM INFOR_PRODUCTO WHERE PRECIO >= 180 ORDER BY PRECIO DESC, NOMBRE ASC;