SELECT MIN(PRICE) AS "Precio menor" FROM PRODUCTS_FUN;

SELECT MAX(PRICE) AS "Precio mayor" FROM PRODUCTS_FUN;

SELECT * FROM PRODUCTS_FUN WHERE Price < 25;

SELECT AVG(PRICE) AS "PRECIO MEDIO" FROM PRODUCTS_FUN;

SELECT PRODUCTNAME FROM PRODUCTS_FUN WHERE CATEGORYID = 2;

SELECT COUNT(DISTINCT CATEGORYID) AS "CANTIDAD DE CATEGORIAS" FROM PRODUCTS_FUN;

SELECT PRODUCTNAME FROM PRODUCTS_FUN WHERE SUPPLIERID = 3;